// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/restaurant/:id": {
    params: {
      "id": string;
    };
  };
  "/coming-soon": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/map" | "/restaurant/:id" | "/coming-soon";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/map.tsx": {
    id: "routes/map";
    page: "/map";
  };
  "routes/restaurant.tsx": {
    id: "routes/restaurant";
    page: "/restaurant/:id";
  };
  "routes/coming-soon.tsx": {
    id: "routes/coming-soon";
    page: "/coming-soon";
  };
};